### PR TITLE
fix: update dependencies to JSR

### PR DESCRIPTION
**Pull request by Milly**
- Fix tasks.
- Fix minimum versions in README.
- Some code fixes due to unknownutil v3.

## Summary by CodeRabbit

- **Documentation**
	- Updated version numbers for Deno, Vim, and Neovim in the README.
	- Changed the link for Deno documentation to reflect the new version.

- **New Features**
	- Enhanced task commands in the Deno configuration for better clarity and control.

- **Improvements**
	- Improved type safety and validations in various functions to ensure stricter checks and better runtime reliability across multiple files.

- **Refactor**
	- Streamlined import statements and type assertions to align with updated modules and libraries.

### CODE REVIEW

**Review by lambdalisue — CHANGES_REQUESTED** [review]
We should not use denops/core

**Comment by Milly** [comment]
I mistakenly thought that the re-export of `@denops/core` from `@dneops/std` had been removed because the "default" export was no longer listed on the [jsr.io doc](https://jsr.io/@denops/std@7.0.1/doc).
Maybe it's a bug in jsr.io?

**Comment by lambdalisue** [comment]
> Maybe it's a bug in jsr.io?

Yes, it seems that re-exported items are unfortunately not listed. We need to report this issue, but I haven't had the chance to do it yet.

**Review by lambdalisue — APPROVED** [review]

**Comment by Milly** [comment]
I forgot to fix CI, but it seems to be disabled now.

**Comment by lambdalisue** [comment]
Oops...

**Pull request merged**
